### ISSUE TITLE
Migrate+update the documentation

### ISSUE THREAD

**Issue by ctrueden** [fiji/dockerfiles#17]
There is [documentation on the ImageJ wiki](https://imagej.net/Docker). In my view it makes sense to migrate that to this repository here, probably into the README. And then update the wiki page to be more of a stub, explaining that ImageJ/Fiji can be used with Docker, and linking to the GitHub repository for the main documentation. (Rule of thumb: end-user-oriented things documented on the wiki; technical/programmer things documented on GitHub and linked from the wiki.)

**Comment by joshmoore** [comment]
@ctrueden I'm happy to move the contents of https://github.com/imagej/imagej.github.io/commit/9a225cd551e49a0f3bdd0267000c07b3e15247e7 into this repo if you are ok to structure the stub as you'd like it.

**Comment by ctrueden** [comment]
@joshmoore Good idea. If you agree, I will add a 301 redirect from https://imagej.net/learn/docker to [the README](https://github.com/fiji/dockerfiles/#readme). Just let me know when you feel it's ready!

**Comment by joshmoore** [comment]
PR opened: #23
