### ISSUE TITLE
Download specific version

### ISSUE THREAD

**Issue by junelsolis** [fiji/dockerfiles#22]
https://github.com/fiji/dockerfiles/blob/faaccb166c6367b2cad47ee2fa4525acf5decef3/fiji-openjdk-8/Dockerfile#L19-L22

Is there a way to download a specific version of Fiji from the download site? I would like to create a Docker image with Fiji locked to a specific version like `2.2.0`. At the moment, I think ``https://downloads.imagej.net/fiji/latest` points to `2.3.1` and `https://downloads.imagej.net/fiji/archive/` only has `2.1.0`

**Comment by ctrueden** [comment]
@junelsolis There are two ways to get a specific version of Fiji:

## From the archive

https://downloads.imagej.net/fiji/archive/

This is all the versions of Fiji that were ever packaged up from the current state of the core update site.

## Using Maven + Git

You can populate a Fiji application from the state of your local Fiji source code. Here is a sequence to clone
```
git clone --branch fiji-2.2.0 git://github.com/fiji/fiji
fiji/bin/populate-app.sh ~/Fiji.app
```
This assumes you already have a copy of Fiji as an application, unpacked at `Fiji.app` in your home directory, which you want to be populated (updated/overwritten) with (e.g.) the 2.2.0 release.

**Comment by junelsolis** [comment]
@ctrueden Thanks for the info! I think `fiji/bin/populate-app.sh` is what I am looking for. I  previously tried to build from source using Maven alone, but that didn't work out. If I'm not mistaken, this same script is also used to build the release files uploaded into [https://downloads.imagej.net/fiji/archive/](https://downloads.imagej.net/fiji/archive/)

> About Fiji Docker images: this repository is not too actively maintained right now, but suggestions are welcome regarding ways we could improve it to be more helpful. And if you have the bandwidth to help keep it updated, that would be most welcome.

I think it would be helpful to have Dockerfiles that are also tagged not only with the Java version but also the Fiji version. For example: `fiji/fiji:2.3.1-openjdk-8`. Not sure if this is a good idea if it runs into conflict with the situation of the update sites. In any case, I'd be happy to contribute Dockerfiles for these tags.
