### ISSUE TITLE
Docker on OS X

### ISSUE THREAD

**Issue by djarecka** [fiji/dockerfiles#4]
Hi, are you planning to update the OS X instruction to run UI. I'm having problems with running and not sure if this is because I'm not using `boot2docker`. I'm just using Docker for Mac.

btw. Does this image can be also used to run ClearVolume?

**Comment by ctrueden** [comment]
@djarecka Sorry, the person who made this repository has left the project, and I have no time to support it or keep it up-to-date. I do think Docker is going to become increasingly prevalent, and I am very interested in seeing this project continue and grow. I am actually in the process of switching to Docker for some of my group's server infrastructure internally, so eventually (in months or years) I will likely revisit this and update it. In the meantime, if anyone else in the community has time and energy, it would be much appreciated!

**Comment by djarecka** [comment]
This is what works in my case, having Docker for Mac:

-  `brew cask install xquartz`

- check `echo $DISPLAY` (if it's empty you can set `export DISPLAY=:0.0`)

- `ip=$(ifconfig en0 | grep inet | awk '$1=="inet" {print $2}')`

- `xhost + $ip`

- `docker run --rm -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=$ip:0 fiji/fiji`

you can read more [here](https://fredrikaverpil.github.io/2016/07/31/docker-for-mac-and-gui-applications/)

**Comment by ctrueden** [comment]
@djarecka Would you have time to submit a small PR to the README here, to include your directions above?

**Comment by djarecka** [comment]
yes, can do it this later this wek
