### ISSUE TITLE
dockerfile/java missing from docker hub

### ISSUE THREAD

**Issue by chigozienri** [fiji/dockerfiles#7]
dockerfile/java has been removed from docker hub, so the Dockerfiles that rely on it in their FROM statements are broken. See https://github.com/dockerfile/java/issues/32
openjdk on dockerhub can be used instead https://hub.docker.com/_/openjdk/

**Comment by ctrueden** [comment]
Fixed by your #8 PR, right?

**Comment by chigozienri** [comment]
Yes, should be fixed by my PR
